---
- name: Write swapfile
  become: true
  command: 'fallocate -l {{ server.swap_size }} /swapfile'
  args:
    creates: /swapfile
  register: write_swapfile

- name: Set swapfile permissions
  become: true
  file:
    path: /swapfile
    mode: 0600

- name: Create swapfile
  become: true
  command: mkswap /swapfile
  register: create_swapfile
  when: write_swapfile.changed

- name: Enable swapfile
  become: true
  command: swapon /swapfile
  when: create_swapfile.changed

- name: Add swapfile to /etc/fstab
  become: true
  lineinfile:
    path: /etc/fstab
    line: '/swapfile none swap sw 0 0'

- name: Configure sysctl.conf
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '{{ item.key }} ?=.*'
    line: '{{ item.key }} = {{ item.value }}'
  notify: Reload sysctl
  with_items: '{{ server.swap_settings }}'
  when: server.swap_settings is defined
