fos_user:
    db_driver: orm
    firewall_name: backoffice
    user_class: App\Entity\User
    from_email:
        address: '%env(MAILER_FROM)%'
        sender_name: Backoffice
    group:
        group_class: App\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
