framework:
    messenger:
        failure_transport: failed
        reset_on_message: true
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            failed: "%env(MESSENGER_TRANSPORT_FAILED_DSN)%"
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
