nelmio_cors:
    paths:
        "^/_storybook/":
            allow_origin: ["*"]
            allow_headers: ["*"]
            allow_methods: ["POST", "PUT", "GET", "DELETE"]
            max_age: 3600
