security:
    enable_authenticator_manager: true
    access_control:
        - { path: ^/backoffice/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            lazy: true
            pattern: /backoffice(.*)
            provider: admin_user_provider
            context: user
            switch_user: true
            logout:
                path: admin_logout
                target: admin_login
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 2629746
                path: /backoffice
            custom_authenticator: App\Security\AdminAuthenticator
    password_hashers:
        App\Entity\User:
            algorithm: auto
    providers:
        admin_user_provider:
            entity:
                class: App\Entity\User
