security:
    enable_authenticator_manager: true
    access_control:
        - { path: ^/backoffice/login$, role: PUBLIC_ACCESS }
        - { path: ^/backoffice/logout$, role: PUBLIC_ACCESS }
        - { path: ^/backoffice/login_check$, role: PUBLIC_ACCESS }
        - { path: ^/backoffice/request$, role: PUBLIC_ACCESS }
        - { path: ^/backoffice/check-email$, role: PUBLIC_ACCESS }
        - { path: ^/backoffice/reset/.*$, role: PUBLIC_ACCESS }
        - { path: ^/backoffice/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            lazy: true
            pattern: /backoffice(.*)
            provider: sonata_user_bundle
            context: user
            switch_user: true
            form_login:
                login_path: sonata_user_admin_security_login
                check_path: sonata_user_admin_security_check
                default_target_path: sonata_admin_dashboard
            logout:
                path: sonata_user_admin_security_logout
                target: sonata_user_admin_security_login
            remember_me:
                secret: "%env(APP_SECRET)%"
                lifetime: 2629746
                path: /backoffice
    password_hashers:
        Sonata\UserBundle\Model\UserInterface:
            algorithm: auto
    providers:
        sonata_user_bundle:
            id: sonata.user.security.user_provider
