security:
    enable_authenticator_manager: true
    access_control:
        - { path: ^/backoffice/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/backoffice/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    # providers:
        # backoffice:
        #     id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # backoffice:
        #     anonymous: lazy
        #     pattern: /backoffice(.*)
        #     provider: backoffice
        #     context: user
        #     switch_user: true
        #     form_login:
        #         login_path: /backoffice/login
        #         check_path: /backoffice/login_check
        #         default_target_path: sonata_admin_dashboard
        #     logout:
        #         path: /backoffice/logout
        #         target: /backoffice/login
        #     remember_me:
        #         secret: '%env(APP_SECRET)%'
        #         lifetime: 2629746
        #         path: /backoffice
