sonata_user:
    class:
        user: App\Entity\User
        group: App\Entity\Group
    impersonating:
        route: sonata_admin_dashboard
    admin:
        user:
            class: App\Admin\UserAdmin
