admin_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /backoffice

admin_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
    prefix: /backoffice
