when@dev:
    _styleguide:
        path: /styleguide
        controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        defaults:
            template: styleguide/styleguide.html.twig
