<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250127123810 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE media__gallery ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE media__gallery ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE user__user ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE user__user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE user__user ALTER roles TYPE JSON USING roles::json;');
        $this->addSql('COMMENT ON COLUMN user__user.roles IS \'\';');
        $this->addSql('ALTER TABLE media__media ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE media__media ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE media__media ALTER provider_metadata TYPE JSONB');
        $this->addSql('ALTER TABLE media__gallery_media ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE media__gallery_media ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE category_translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE category_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE category ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE book ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE book ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE book_translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE book_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE contact ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE contact ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE contact ALTER preferences TYPE TEXT;');
        $this->addSql('ALTER TABLE contact ALTER date TYPE TIMESTAMP(0) WITHOUT TIME ZONE;');
        $this->addSql('COMMENT ON COLUMN contact.preferences IS \'\';');
        $this->addSql('COMMENT ON COLUMN contact.date IS \'\';');
        $this->addSql('ALTER TABLE basic_page_translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE basic_page_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE basic_page ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE basic_page ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE cookies_page_translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE cookies_page_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE cookies_page ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE cookies_page ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE redirect ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE redirect ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE entity_meta_information ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE entity_meta_information ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE meta_information ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE meta_information ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE entity_meta_information_translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE entity_meta_information_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE meta_information_translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE meta_information_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE translation_translation ALTER id TYPE INT;');
        $this->addSql('ALTER TABLE translation_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT;');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE;');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE;');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE;');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\';');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\';');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\';');
    }

    public function down(Schema $schema): void
    {
    }
}
