<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241022081033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE basic_page ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE basic_page ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE basic_page_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE basic_page_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE book ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE book ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE book_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE book_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE category_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE category_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE contact ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE contact ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE contact ALTER preferences TYPE TEXT');
        $this->addSql('ALTER TABLE contact ALTER date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN contact.preferences IS \'\'');
        $this->addSql('COMMENT ON COLUMN contact.date IS \'\'');
        $this->addSql('ALTER TABLE cookies_page ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE cookies_page ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cookies_page_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE cookies_page_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE entity_meta_information ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE entity_meta_information ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE entity_meta_information_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE entity_meta_information_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE media__gallery ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE media__gallery ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE media__gallery_media ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE media__gallery_media ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE media__media ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE media__media ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE meta_information ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE meta_information ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE meta_information_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE meta_information_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE redirect ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE redirect ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE translation_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE translation_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE user__user ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user__user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category ALTER id SET DEFAULT category_id_seq');
        $this->addSql('ALTER TABLE category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE entity_meta_information ALTER id SET DEFAULT entity_meta_information_id_seq');
        $this->addSql('ALTER TABLE entity_meta_information ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE basic_page ALTER id SET DEFAULT basic_page_id_seq');
        $this->addSql('ALTER TABLE basic_page ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE basic_page_translation ALTER id SET DEFAULT basic_page_translation_id_seq');
        $this->addSql('ALTER TABLE basic_page_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE translation_translation ALTER id SET DEFAULT translation_translation_id_seq');
        $this->addSql('ALTER TABLE translation_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE translation ALTER id SET DEFAULT translation_id_seq');
        $this->addSql('ALTER TABLE translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE meta_information_translation ALTER id SET DEFAULT meta_information_translation_id_seq');
        $this->addSql('ALTER TABLE meta_information_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE meta_information ALTER id SET DEFAULT meta_information_id_seq');
        $this->addSql('ALTER TABLE meta_information ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE redirect ALTER id SET DEFAULT redirect_id_seq');
        $this->addSql('ALTER TABLE redirect ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE contact ALTER id SET DEFAULT contact_id_seq');
        $this->addSql('ALTER TABLE contact ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE contact ALTER preferences TYPE TEXT');
        $this->addSql('ALTER TABLE contact ALTER date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN contact.preferences IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN contact.date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE media__gallery_media ALTER id SET DEFAULT media__gallery_media_id_seq');
        $this->addSql('ALTER TABLE media__gallery_media ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE media__gallery ALTER id SET DEFAULT media__gallery_id_seq');
        $this->addSql('ALTER TABLE media__gallery ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE user__user ALTER id SET DEFAULT user__user_id_seq');
        $this->addSql('ALTER TABLE user__user ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE entity_meta_information_translation ALTER id SET DEFAULT entity_meta_information_translation_id_seq');
        $this->addSql('ALTER TABLE entity_meta_information_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cookies_page_translation ALTER id SET DEFAULT cookies_page_translation_id_seq');
        $this->addSql('ALTER TABLE cookies_page_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cookies_page ALTER id SET DEFAULT cookies_page_id_seq');
        $this->addSql('ALTER TABLE cookies_page ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE category_translation ALTER id SET DEFAULT category_translation_id_seq');
        $this->addSql('ALTER TABLE category_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE book_translation ALTER id SET DEFAULT book_translation_id_seq');
        $this->addSql('ALTER TABLE book_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE media__media ALTER id SET DEFAULT media__media_id_seq');
        $this->addSql('ALTER TABLE media__media ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE book ALTER id SET DEFAULT book_id_seq');
        $this->addSql('ALTER TABLE book ALTER id DROP IDENTITY');
    }
}
