runroom.cookies.route.cookies:
    path:
        es: /politica-de-cookies
        ca: /politica-de-cookies
        en: /cookies-policy
    controller: Runroom\CookiesBundle\Controller\CookiesPageController::index
