services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $cookies: '%cookies%'

    Runroom\CookiesBundle\:
        resource: ../../*

    Runroom\CookiesBundle\Controller\:
        resource: ../../Controller
        public: true
        tags: [controller.service_arguments]

    Runroom\CookiesBundle\Admin\CookiesPageAdmin:
        public: true
        arguments: [null, Runroom\CookiesBundle\Entity\CookiesPage, null]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Cookies' }
