version: '3'

services:
    app:
        volumes:
            - ../:/srv/app/:cached
            - /srv/app/var/
            - /srv/app/node_modules/
    nginx:
        volumes:
            - ../.certs:/srv/app/.certs:ro,cached
            - ../public:/srv/app/public:ro,cached
            - ../vendor:/srv/app/vendor:ro,cached
