version: '3'

services:
    app:
        volumes:
            - ../:/usr/app/:cached
            - /usr/app/var/
            - /usr/app/node_modules/
            - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
        environment:
            - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    nginx:
        volumes:
            - ../.certs:/usr/app/.certs:ro,cached
            - ../public:/usr/app/public:ro,cached
            - ../vendor:/usr/app/vendor:ro,cached
