version: '3'

services:
    app:
        volumes:
            - ..:/srv/app:delegated
            - /srv/app/node_modules/
            - /srv/app/var/
    nginx:
        volumes:
            - ..:/srv/app:delegated
            - /srv/app/node_modules/
            - /srv/app/var/
