version: '2'

syncs:
    archetype-sync:
        src: ..
        sync_excludes: [node_modules, var, .git]
        host_disk_mount_mode: cached
        native_osx_image: eugenmayer/unison:2.51.2.2

options:
    compose-file-path: docker-compose.yaml
    compose-dev-file-path: docker-compose-sync.yaml
