version: '3'

services:
    app:
        volumes:
            - archetype-sync:/srv/app:nocopy
            - /srv/app/node_modules/
            - /srv/app/var/
    nginx:
        volumes:
            - archetype-sync:/srv/app:nocopy
            - /srv/app/node_modules/
            - /srv/app/var/

volumes:
    archetype-sync:
        external: true
