version: '3'

services:
    app:
        volumes:
            - ../:/srv/app/:cached
            - /srv/app/node_modules/
            - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
        environment:
            - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    nginx:
        volumes:
            - ../.certs:/srv/app/.certs:cached
            - ../public:/srv/app/public:cached
            - ../vendor:/srv/app/vendor:cached
