services:
    runroom.seo.admin.meta_information:
        class: Runroom\SeoBundle\Admin\MetaInformationAdmin
        public: true
        arguments: [~, Runroom\SeoBundle\Entity\MetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'SEO' }

    runroom.seo.admin.entity_meta_information:
        class: Runroom\SeoBundle\Admin\EntityMetaInformationAdmin
        public: true
        arguments: [~, Runroom\SeoBundle\Entity\EntityMetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Entity SEO' }
