services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'

    Runroom\SeoBundle\:
        resource: ../../*

    Runroom\SeoBundle\MetaInformation\MetaInformationService:
        bind:
            $providers: !tagged seo.meta_information

    Runroom\SeoBundle\AlternateLinks\AlternateLinksService:
        bind:
            $providers: !tagged seo.alternate_links
