# SonataAdminBundle
sonata_admin:
    resource: .
    type: sonata_admin

backoffice:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"

# SonataMediaBundle
media:
    resource: "@SonataMediaBundle/Resources/config/routing/media.xml"
    prefix: /media

# SonataUserBundle
admin_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"

admin_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
