runroom_samples:
    resource: "@RunroomSamplesBundle/Resources/config/routing.yaml"

runroom_cookies:
    resource: "@RunroomCookiesBundle/Resources/config/routing.yaml"

controllers:
    resource:
        path: ../src/Action/
        namespace: App\Action
    type: attribute

# Must be the last one
runroom_basic_page:
    resource: "@RunroomBasicPageBundle/Resources/config/routing.yaml"
