parameters:
    locale: en
    xdefault_locale: en
    locales: [en, es, ca]
    doctrine_behaviors_translatable_fetch_mode: EAGER
    doctrine_behaviors_translation_fetch_mode: EAGER

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $locales: "%locales%"

    # Autowire
    Jaybizzle\CrawlerDetect\CrawlerDetect: null

    # External services
    Gedmo\Sluggable\SluggableListener:
        calls: [[setAnnotationReader, ["@annotation_reader"]]]
        tags: [doctrine.event_subscriber]

    Gedmo\Sortable\SortableListener:
        calls: [[setAnnotationReader, ["@annotation_reader"]]]
        tags: [doctrine.event_subscriber]

    # Services
    App\:
        resource: ../src/*
        exclude:
            - ../src/Entity/
            - ../src/Kernel.php

    App\Controller\:
        resource: ../src/Controller
        public: true
        tags: [controller.service_arguments]

    App\Service\MailService:
        bind:
            $from: "%env(MAILER_FROM)%"
            $bcc: "%env(json:MAILER_BCC)%"

    sonata.admin.manager.random:
        class: App\Model\ModelManager
        tags: [sonata.admin.manager]

    sonata.admin.data_source.random:
        class: App\Model\DataSource

    sonata.admin.field_description_factory.random:
        class: App\Model\FieldDescriptionFactory

    sonata.admin.builder.random_form:
        class: App\Model\FormContractor

    sonata.admin.builder.random_show:
        class: App\Model\ShowBuilder

    sonata.admin.builder.random_list:
        class: App\Model\ListBuilder

    sonata.admin.builder.random_datagrid:
        class: App\Model\DatagridBuilder

    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\DTO\Random,
                  manager_type: random,
                  group: admin,
                  label: User
              }

when@dev:
    services:
        App\EventListener\FixPostgreSQLDefaultSchemaListener:
            tags:
                - { name: doctrine.event_listener, event: postGenerateSchema }
