<?php

namespace Application\Sonata\MediaBundle\PHPCR;

use Sonata\MediaBundle\PHPCR\BaseGalleryRepository;

/**
 * This file has been generated by the EasyExtends bundle ( https://sonata-project.org/bundles/easy-extends ).
 *
 * References :
 *   query builder     : http://www.doctrine-project.org/docs/mongodb_odm/1.0/en/reference/query-builder-api.html
 *
 * @author <yourname> <youremail>
 */
class GalleryRepository extends BaseGalleryRepository
{
}
