services:
    app:
        build:
            target: app-dev
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            APP_ENV: dev
            APP_DEBUG: 1
        volumes:
            - ../:/usr/app/:cached
            - /usr/app/node_modules/
        extra_hosts:
            - host.docker.internal:${XDEBUG_HOST:-host-gateway}
