services:
    app:
        build:
            target: app-prod
        depends_on:
            database:
                condition: service_healthy
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            RESET_DATABASE: "${RESET_DATABASE:-false}"
            MIGRATE_DATABASE: "${MIGRATE_DATABASE:-false}"
        volumes:
            - ../public/uploads:/usr/app/public/uploads
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://127.0.0.1:2019/metrics
            interval: 5s
    database:
        healthcheck:
            test: pg_isready --username $${POSTGRES_USER}
            interval: 5s
