volumes:
    test:

services:
    app:
        build:
            target: fpm-prod
        depends_on:
            database:
                condition: service_healthy
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            RESET_DATABASE: false
        volumes:
            - test:/usr/app/public
        healthcheck:
            test: ["CMD", "healthcheck"]
            start_period: 1m
            interval: 10s
    nginx:
        build:
            target: nginx-prod
        depends_on:
            app:
                condition: service_started
        volumes:
            - test:/usr/app/public
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            start_period: 1m
            interval: 10s
    database:
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
