services:
    app:
        build:
            target: app-prod
        depends_on:
            database:
                condition: service_healthy
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            RESET_DATABASE: "${RESET_DATABASE:-false}"
            MIGRATE_DATABASE: "${MIGRATE_DATABASE:-false}"
        volumes:
            - ../public/uploads:/usr/app/public/uploads
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
            interval: 5s
    database:
        healthcheck:
            test: ["CMD-SHELL", "pg_isready --username $${POSTGRES_USER}"]
            interval: 5s
