runroom_user_forgot_password_request:
    path: /reset-password
    controller: runroom_user.controller.reset_password::request

runroom_user_check_email:
    path: /reset-password/check-email
    controller: runroom_user.controller.reset_password::checkEmail

runroom_user_reset_password:
    path: /reset-password/reset/{token?}
    controller: runroom_user.controller.reset_password::reset
