services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Runroom\StaticPageBundle\:
        resource: ../../*

    Runroom\StaticPageBundle\Controller\:
        resource: ../../Controller
        public: true
        tags: [controller.service_arguments]
