---
- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer

- name: Create composer directory
  file:
    path: '{{ ansible_env.HOME }}/bin'
    state: directory

- name: Install composer
  command: 'php /tmp/composer-installer --install-dir={{ ansible_env.HOME }}/bin --filename=composer'
  args:
    creates: '{{ ansible_env.HOME }}/bin/composer'

- name: Install global composer packages
  composer:
    global_command: yes
    command: require
    arguments: "{{ item.package }} {{ item.version|default('@stable') }}"
  with_items: '{{ composer.packages }}'
  when: composer.packages is defined
  environment:
    PATH: '/home/vagrant/bin:/usr/bin'
