name: deployment

on: [deployment]

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3']
    env:
      DEPLOYER_USER: ${{ secrets.DEPLOYER_USER }}
    steps:
      - uses: actions/checkout@v2
      - uses: deliverybot/deployment-status@v1
        with:
          state: pending
          token: ${{ github.token }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php }}-composer
      - run: composer install --prefer-dist --no-progress --no-interaction --no-scripts
      - run: ssh-keyscan ${{ github.event.deployment.payload.url }} >> ~/.ssh/known_hosts
      - run: vendor/bin/dep deploy ${{ github.event.deployment.environment }}
      - uses: deliverybot/deployment-status@v1
        if: success()
        with:
          state: success
          token: ${{ github.token }}
          environment-url: ${{ github.event.deployment.payload.url }}
      - uses: deliverybot/deployment-status@v1
        if: failure()
        with:
          state: failure
          token: ${{ github.token }}
