name: Manual deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: Staging
                type: choice
                options:
                    - Production
                    - Staging

jobs:
    manual:
        name: ${{ inputs.environment }}
        runs-on: ubuntu-latest
        concurrency: ${{ inputs.environment }}
        environment: ${{ inputs.environment }}
        strategy:
            matrix:
                php: ["8.1"]
        env:
            DEPLOYER_USER: ${{ secrets.DEPLOYER_USER }}
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
            - uses: ramsey/composer-install@v2
            - shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            - uses: deployphp/action@v1
              with:
                  private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known-hosts: ${{ secrets.KNOWN_HOSTS }}
                  dep:
                      -vv deploy ${{ secrets.HOST }} --branch=${{
                      steps.extract_branch.outputs.branch }}
