name: Manual deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                type: environment

jobs:
    manual:
        name: ${{ inputs.environment }}
        runs-on: ubuntu-latest
        concurrency: ${{ inputs.environment }}
        environment: ${{ inputs.environment }}
        strategy:
            matrix:
                php: ["8.2"]
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - uses: ramsey/composer-install@v2
            - uses: bahmutov/npm-install@v1
            - run: npm run build
            - shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            - uses: deployphp/action@v1
              with:
                  private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known-hosts: ${{ secrets.KNOWN_HOSTS }}
                  dep:
                      deploy symfony.runroom.dev --branch=${{ steps.extract_branch.outputs.branch }}
              env:
                  DEPLOYER_HOST: ${{ secrets.DEPLOYER_HOST }}
                  DEPLOYER_USER: ${{ secrets.DEPLOYER_USER }}
