name: PR Deploy

on:
    issue_comment:

jobs:
    slash-command:
        name: Slash Command
        runs-on: ubuntu-latest
        steps:
            - uses: xt0rted/slash-command-action@v1
              with:
                  command: deploy
                  reaction-type: rocket

    deploy:
        name: Deploy
        needs: slash-command
        uses: runroom/archetype-symfony/.github/workflows/deploy.yaml@main
        with:
            environment: staging
            tag: pr-${{ github.event.number }}
        secrets: inherit
